### ISSUE TITLE
Link checker issue

### ISSUE THREAD

**Issue by tohuynh** [SIGLA-GU/siglatools#46]
Hi @tohuynh, hope you are well!

When we went through the link checker last time, we noticed a small issue that came up when urls had commas in them. A lot of links came back as broken because the system thought the url ended earlier than it actually did. (Example: "https://www.registraduria.gov.co/-Pedagogia,4337-.html" came up as "https://www.registraduria.gov.co/-Pedagogia")

I imagine this is because the program is reading the database with commas as separations between cells/data points, right? Is there an easy way to switch to another method of denoting separate urls (perhabs tab/spaces or some other divisor rather than commas)? Or do you have any other ideas for preventing this from happening in the future? Thanks in advance!

Kind Regards,
Felipe Lobo Koerich

**Comment by tohuynh** [comment]
@flobokoerich Could you post more examples like the one above? And include the location of these URLs in the PROD sheets

**Comment by flobokoerich** [comment]
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E111 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E112 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E113 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E114 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E115 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E116 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SIGLA_Data_Elections_PROD-LAUNCH_20210917 | Electoral Results Colombia PROD | E117 | https://www.registraduria.gov.co/-Pedagogia |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

</google-sheets-html-origin>

**Comment by flobokoerich** [comment]
I think all the examples we have are of this website (which makes sense, I don't think I've ever seen a comma in a url)

Let me know if the above works, or if you need more information!

**Comment by tohuynh** [comment]
Thanks, I think that's enough for me to investigate the cause of the issue.

**Comment by tohuynh** [comment]
The script was able to find `https://www.registraduria.gov.co/-Pedagogia,4337-.html` in its entirety. It's a "broken" link because the script was unable to connect to the URL despite trying multiple times (It got a request timed out error).  I'm not sure why `,4337-.html` wasn't included in your examples above, but in the artifact file csv file (that is tab-delimited, not comma delimited) the full URL is there. See the external [artifact](https://github.com/SIGLA-GU/siglatools/actions/runs/1545754891)

**Comment by flobokoerich** [comment]
Thanks To! Must clearly be an error on our end, I will investigate.
