### ISSUE TITLE
Change Amendments Table Title to Variable Name 

### ISSUE THREAD

**Issue by louisachristen** [SIGLA-GU/siglatools#5]
## Description
*A clear description of the bug*
Right now, the title of the amendments table is 'All Amendments.' This might be a bit misleading. 

## Expected Behavior
*What did you expect to happen instead?*
We would like the title of the Amendments table to be the Amendments variable name from the Constitution SIT: "‘Amendments to most recent constitution."

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

**Comment by tohuynh** [comment]
I was wrong about about where this issue should be created. I only needed to change a couple of line of codes in `sigla-web` to fix this problem. You don't need to move this to `sigla-web`. I'll just reference this issue with the corresponding pull-request.

**Comment by tohuynh** [comment]
This issue is resolved by [sigla-web #40](https://github.com/SIGLA-GU/sigla-web/pull/40)
