### ISSUE TITLE
link checker error

### ISSUE THREAD

**Issue by PX15-gtown** [SIGLA-GU/siglatools#58]
Hi To -- hope all is well with you. 

Per Professor Kapiszewski's slack, we ran the External Linkchecker and received this warning; we wanted to check with you about what it means, and if we need to do anything, and if we can proceed with the linkchecker output. 

Annotations
1 warning
[external_link_checker ](https://github.com/SIGLA-GU/siglatools/actions/runs/7924064020/job/21634977526)Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by PX15-gtown** [comment]
![image](https://github.com/SIGLA-GU/siglatools/assets/160270433/e849a046-6f37-4312-88fd-999052d71f95)

**Comment by tohuynh** [comment]
@PX15-gtown I upgraded the GitHub actions to use versions that uses Node.js 20.

Let me know if there are any other warnings when running the workflows.
